server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:9002
          predicates:
            - Path=/users/**
            
        - id: authentication-service
          uri: http://localhost:9001
          predicates:
            - Path=/auth/**
            
        - id: email-service
          uri: http://localhost:9004
          predicates:
            - Path=/mail/**
      discovery:
        locator:
          enabled: true
          
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/VanLQ
          
jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP
